<?php
/**
 * @file
 * Hooks and callbacks for the Serial solution pack module.
 */

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_serial_object_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_serial_object');
  $islandora_path = drupal_get_path('module', 'islandora');
  // Serial model.
  $serial_content_model = $connection->repository->constructObject('islandora:rootSerialCModel');
  $serial_content_model->owner = 'fedoraAdmin';
  $serial_content_model->label = 'Islandora Serial Object Content Model';
  $serial_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL datastream.
  $datastream = $serial_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_serial_object_ds_composite_model.xml", FALSE);
  $serial_content_model->ingestDatastream($datastream);

  // Intermediate content model.
  $intermediate_content_model = $connection->repository->constructObject('islandora:intermediateSerialCModel');
  $intermediate_content_model->owner = 'fedoraAdmin';
  $intermediate_content_model->label = 'Islandora Serial Object Intermediate Content Model';
  $intermediate_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL datastream.
  $datastream = $intermediate_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_serial_object_intermediate_ds_composite_model.xml", FALSE);
  $intermediate_content_model->ingestDatastream($datastream);

  // Serial collection.
  $serial_collection = $connection->repository->constructObject('islandora:serial_collection');
  $serial_collection->owner = 'fedoraAdmin';
  $serial_collection->label = 'Serial Collection';
  $serial_collection->models = 'islandora:collectionCModel';
  $serial_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection policy datastream.
  $datastream = $serial_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection/islandora_serial_object_collection_policy.xml", FALSE);
  $serial_collection->ingestDatastream($datastream);
  // TN datastream.
  $datastream = $serial_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $serial_collection->ingestDatastream($datastream);

  return array(
    'islandora_serial_object' => array(
      'title' => 'Islandora Serial',
      'objects' => array(
        $serial_content_model,
        $intermediate_content_model,
        $serial_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_serial_object_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_serial_object_mods_form' => array(
      'content_model' => 'islandora:rootSerialCModel',
      'form_name' => 'Islandora Serial Object MODS form',
      'dsid' => 'MODS',
      'title_field' => array(
        'titleInfoTab',
        'titleInfoPanel',
        'titleInfo',
        'title',
      ),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_serial_object_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_serial_object');
  return array(
    'Islandora Serial Object MODS form' => array(
      'form_file' => "$module_path/xml/forms/islandora_serial_object_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_serial_object_islandora_rootSerialCModel_islandora_ingest_steps() {
  return array(
    'islandora_serial_object' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_serial_object_add_intermediate_form',
      'module' => 'islandora_serial_object',
      'file' => 'includes/ingest.form.inc',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_serial_object_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_serial_object_intermediates_table' => array(
      'render element' => 'form',
      'file' => 'theme/theme.inc',
    ),
  );
}
